# Setup
title:               HoonK212
tagline:             GitHub_Blog
description:         '안녕하세요'
url:                 https://hoonk212.github.io/
baseurl:             ''
paginate:            12
permalink:           pretty

# About/contact
author:
  name:              Hoon Kim
  url:               https://hoonk212.github.io/
  email:             b0aeiou@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
